logging:
  path: ./logs/
spring:
  data:
    mongodb:
      uri: mongodb://DocTool:123456@localhost:27019/DocTool
  application:
    name: treatmentService
server:
  tomcat:
    uri-encoding: utf-8
sso:
  redis:
    address: redis://myRedis:123456@127.0.0.1:6379
    expire:
      minite: 1440
eureka:
  client:
    service-url:
      DEFAULT_ZONE: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/