logging:
  path: ./logs/
spring:
  data:
    mongodb:
      uri: mongodb://DocTool:123456@120.79.79.151:27017/DocTool?maxPoolSize=50&connectTimeoutMS=30000&socketTimeoutMS=3000
  application:
    name: treatmentService-server
server:
  tomcat:
    uri-encoding: utf-8
sso:
  redis:
    address: redis://myRedis:123456@120.79.79.151:6379
    expire:
      minite: 1440
eureka:
  client:
    service-url:
      DEFAULT_ZONE: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/